// Code generated by protoc-gen-gogo.
// source: record.proto
// DO NOT EDIT!

/*
Package wal is a generated protocol buffer package.

It is generated from these files:
	record.proto

It has these top-level messages:
	Record
*/
package wal

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Record struct {
	Index            uint64 `protobuf:"varint,1,req,name=index" json:"index"`
	Prev             uint64 `protobuf:"varint,2,req,name=prev" json:"prev"`
	Type             int64  `protobuf:"varint,3,opt,name=type" json:"type"`
	Crc              uint32 `protobuf:"varint,4,req,name=crc" json:"crc"`
	Data             []byte `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}

func (m *Record) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Record) GetPrev() uint64 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *Record) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Record) GetCrc() uint32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *Record) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
